# include: package:dart_flutter_team_lints/analysis_options.yaml
 include: package:lint_hard/all.yaml
 analyzer:
   errors:
     constant_identifier_names: ignore
     sort_constructors_first: ignore
     sort_unnamed_constructors_first: ignore

